[workspace]
resolver = "3"
members = ["crates/config", "crates/engine", "crates/replay-cli"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"

[workspace.dependencies]
arrayvec = { version = "0.7", default-features = false }
bitflags = { version = "2", default-features = false }
serde = { version = "1", default-features = false, features = ["derive"] }

[profile.release]
lto = true
codegen-units = 1
